src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    private ?Youssef $user = null;

    #[ORM\Column]
    private ?int $table_number = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $reservation_time = null;

    #[ORM\Column(length: 50)]
    private ?string $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Youssef
    {
        return $this->user;
    }

    public function setUser(?Youssef $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getTableNumber(): ?int
    {
        return $this->table_number;
    }

    public function setTableNumber(int $table_number): static
    {
        $this->table_number = $table_number;

        return $this;
    }

    public function getReservationTime(): ?\DateTimeInterface
    {
        return $this->reservation_time;
    }

    public function setReservationTime(\DateTimeInterface $reservation_time): static
    {
        $this->reservation_time = $reservation_time;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use App\Entity\Youssef;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('table_number')
            ->add('reservation_time', null, [
                'widget' => 'single_text',
            ])
            ->add('status')
            ->add('user', EntityType::class, [
                'class' => Youssef::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/reservation')]
final class ReservationController extends AbstractController
{
    #[Route(name: 'app_reservation_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}
    <h1>Reservation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Table_number</th>
                <th>Reservation_time</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.tableNumber }}</td>
                <td>{{ reservation.reservationTime ? reservation.reservationTime|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ reservation.status }}</td>
                <td>
                    <a href="{{ path('app_reservation_show', {'id': reservation.id}) }}">show</a>
                    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_reservation_new') }}">Create new</a>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Table_number</th>
                <td>{{ reservation.tableNumber }}</td>
            </tr>
            <tr>
                <th>Reservation_time</th>
                <td>{{ reservation.reservationTime ? reservation.reservationTime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ reservation.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}