src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Youssef $user = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Menu $menu_items = null;

    #[ORM\Column]
    private ?float $total_price = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $order_time = null;

    #[ORM\Column(length: 50)]
    private ?string $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Youssef
    {
        return $this->user;
    }

    public function setUser(?Youssef $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getMenuItems(): ?Menu
    {
        return $this->menu_items;
    }

    public function setMenuItems(?Menu $menu_items): static
    {
        $this->menu_items = $menu_items;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->total_price;
    }

    public function setTotalPrice(float $total_price): static
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getOrderTime(): ?\DateTimeInterface
    {
        return $this->order_time;
    }

    public function setOrderTime(\DateTimeInterface $order_time): static
    {
        $this->order_time = $order_time;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Menu;
use App\Entity\Order;
use App\Entity\Youssef;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('total_price')
            ->add('order_time', null, [
                'widget' => 'single_text',
            ])
            ->add('status')
            ->add('user', EntityType::class, [
                'class' => Youssef::class,
                'choice_label' => 'id',
            ])
            ->add('menu_items', EntityType::class, [
                'class' => Menu::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\OrderType;
use App\Repository\OrderRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/order')]
final class OrderController extends AbstractController
{
    #[Route(name: 'app_order_index', methods: ['GET'])]
    public function index(OrderRepository $orderRepository): Response
    {
        return $this->render('order/index.html.twig', [
            'orders' => $orderRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_order_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $order = new Order();
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($order);
            $entityManager->flush();

            return $this->redirectToRoute('app_order_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('order/new.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_order_show', methods: ['GET'])]
    public function show(Order $order): Response
    {
        return $this->render('order/show.html.twig', [
            'order' => $order,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_order_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Order $order, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_order_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('order/edit.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_order_delete', methods: ['POST'])]
    public function delete(Request $request, Order $order, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_order_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/order/_delete_form.html.twig
<form method="post" action="{{ path('app_order_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

templates/order/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/order/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Order{% endblock %}

{% block body %}
    <h1>Edit Order</h1>

    {{ include('order/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_order_index') }}">back to list</a>

    {{ include('order/_delete_form.html.twig') }}
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order index{% endblock %}

{% block body %}
    <h1>Order index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Total_price</th>
                <th>Order_time</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.totalPrice }}</td>
                <td>{{ order.orderTime ? order.orderTime|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ order.status }}</td>
                <td>
                    <a href="{{ path('app_order_show', {'id': order.id}) }}">show</a>
                    <a href="{{ path('app_order_edit', {'id': order.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_order_new') }}">Create new</a>
{% endblock %}

templates/order/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Order{% endblock %}

{% block body %}
    <h1>Create new Order</h1>

    {{ include('order/_form.html.twig') }}

    <a href="{{ path('app_order_index') }}">back to list</a>
{% endblock %}

templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    <h1>Order</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order.id }}</td>
            </tr>
            <tr>
                <th>Total_price</th>
                <td>{{ order.totalPrice }}</td>
            </tr>
            <tr>
                <th>Order_time</th>
                <td>{{ order.orderTime ? order.orderTime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ order.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_order_index') }}">back to list</a>

    <a href="{{ path('app_order_edit', {'id': order.id}) }}">edit</a>

    {{ include('order/_delete_form.html.twig') }}
{% endblock %}